package com.example.database

import com.example.database.entity.NoteEntity
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

internal class NoteDaoTest : DatabaseTest() {

    @Test
    fun newDatabaseReturnsEmptyList() = runTest {
        assertEquals(emptyList<NoteEntity>(), noteDao.getAllNotes().first())
    }

    @Test
    fun insertedNoteCanBeObservedById() = runTest {
        val note = testNote(id = 1)

        noteDao.insert(note)

        assertEquals(note, noteDao.getNote(note.id).first())
    }

    @Test
    fun unknownIdReturnsNull() = runTest {
        assertEquals(null, noteDao.getNote(id = 404).first())
    }

    @Test
    fun insertedNotesAreOrderedByCreatedAtDescending() = runTest {
        val oldest = testNote(id = 1, createdAt = 100)
        val newest = testNote(id = 2, createdAt = 300)
        val middle = testNote(id = 3, createdAt = 200)

        noteDao.insert(oldest)
        noteDao.insert(newest)
        noteDao.insert(middle)

        assertEquals(
            listOf(newest, middle, oldest),
            noteDao.getAllNotes().first(),
        )
    }

    @Test
    fun updateChangesEveryMutableField() = runTest {
        val original = testNote(id = 1)
        val updated = original.copy(
            title = "Updated title",
            plainText = "Updated content",
            contentJson = """{"version":1,"text":"Updated content"}""",
            createdAt = 200,
            updatedAt = 300,
            isPinned = true,
            isArchieved = true,
            color = "blue",
            tags = listOf("updated", "room"),
        )

        noteDao.insert(original)
        noteDao.update(updated)

        assertEquals(updated, noteDao.getNote(original.id).first())
    }

    @Test
    fun deleteRemovesTheNote() = runTest {
        val note = testNote(id = 1)

        noteDao.insert(note)
        noteDao.delete(note)

        assertEquals(null, noteDao.getNote(note.id).first())
    }

    @Test
    fun duplicateIdIsIgnoredWithoutOverwritingExistingNote() = runTest {
        val original = testNote(id = 1, title = "Original")
        val duplicate = testNote(id = 1, title = "Replacement")

        noteDao.insert(original)
        noteDao.insert(duplicate)

        assertEquals(original, noteDao.getNote(original.id).first())
    }

    @Test
    fun updatingUnknownIdDoesNotInsertANote() = runTest {
        noteDao.update(testNote(id = 404))

        assertEquals(emptyList<NoteEntity>(), noteDao.getAllNotes().first())
    }

    @Test
    fun deletingUnknownIdDoesNotChangeOtherNotes() = runTest {
        val stored = testNote(id = 1)

        noteDao.insert(stored)
        noteDao.delete(testNote(id = 404))

        assertEquals(listOf(stored), noteDao.getAllNotes().first())
    }


    @Test
    fun zeroIdIsReplacedWithAnAutoGeneratedId() = runTest {
        noteDao.insert(testNote(id = 0))

        val stored = noteDao.getAllNotes().first().single()

        assertTrue(stored.id > 0)
    }

    @Test
    fun allNotesReflectInsertUpdateAndDeleteOperations() = runTest {
        val original = testNote(id = 1, title = "Original")
        val updated = original.copy(title = "Updated", updatedAt = 200)

        noteDao.insert(original)
        assertEquals(listOf(original), noteDao.getAllNotes().first())

        noteDao.update(updated)
        assertEquals(listOf(updated), noteDao.getAllNotes().first())

        noteDao.delete(updated)
        assertEquals(emptyList<NoteEntity>(), noteDao.getAllNotes().first())
    }
}

private fun testNote(
    id: Long,
    title: String = "Title $id",
    plainText: String = "Content $id",
    contentJson: String = """{"version":1,"text":"Content $id"}""",
    createdAt: Long = 100,
    updatedAt: Long = createdAt,
    isPinned: Boolean = false,
    isArchieved: Boolean = false,
    color: String? = null,
    tags: List<String> = listOf("room", "test"),
) = NoteEntity(
    id = id,
    title = title,
    plainText = plainText,
    contentJson = contentJson,
    createdAt = createdAt,
    updatedAt = updatedAt,
    isPinned = isPinned,
    isArchieved = isArchieved,
    color = color,
    tags = tags,
)
